name: CD
on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    env:
      UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}    
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Publish
        run: just publish
