name: Upload release to PyPI

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - name: Setup mamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: env.yaml
    - name: Install package with requirements
      run: poetry install --no-dev
    - name: Build and publish
      env:
        POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
      run: poetry publish --build
