name: Upload release to PyPI

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - name: Setup mamba
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: env.yaml
    - name: Build and publish
      env:
        HATCH_INDEX_USER: __token__
        HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
      run: hatch build && hatch publish
