name: CI
on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test_and_lint:
    name: Test and lint
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: true
    - name: Setup conda
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package with test dependencies
      run: pip install .[tests]
    - name: Run PyTest
      run: pytest
    - name: Run Flake8
      run: flake8
    - name: Run mypy
      run: mypy .
    - name: Run Black
      run: black --check .
    - name: Run isort
      run: isort --check-only .