name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: env.yaml
          extra-specs: python=3.9
      - name: Lint
        run: make lint

  test:
    name: Test
    runs-on: ${{ matrix.operating-system }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup mamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: env.yaml
          extra-specs: python=${{ matrix.python-version }}
      - name: Install package with requirements
        run: pip install -e .
      - name: Run PyTest
        run: pytest
